### ISSUE TITLE
Translation Switcher Problem

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/LG#1]
![screen shot 2018-09-08 at 12 09 15 pm](https://user-images.githubusercontent.com/12680304/45250331-64424900-b363-11e8-9159-83e193c3824d.png)

**Comment by mikedesigner** [comment]
Maybe you need to add some filter in the custom post archive page? Found some code that may help....

![screen shot 2018-09-12 at 5 58 58 pm](https://user-images.githubusercontent.com/12680304/45417873-be217680-b6b5-11e8-95bd-a3121b90045b.png)

**Comment by cezarys** [comment]
seems to be fixed

**Comment by mikedesigner** [comment]
Yeah
