### ISSUE TITLE
On Artworks individual pages and Originals individual pages please allow for multiple categories to be seen.

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/LG#10]
Some limited editions, open editions, and originals will belong to mutliple categories. We tested this out and only 1 category shows up on the front-end even though we have selected multiple categories in the back-end.  We need to see multiple categories here and they should be linked to the category archive page ( if I click on any of these category names, example: "Landscape" I go to a page which shows all items from limited editions, open editions, and originals that belong to the category "Landscape".
![screen shot 2018-09-08 at 6 38 47 pm](https://user-images.githubusercontent.com/12680304/45253243-a9cc3980-b396-11e8-8671-451152f7fafe.png)

**Comment by cezarys** [comment]
This one should be done

**Comment by mikedesigner** [comment]
Yes its done. closing.
