### ISSUE TITLE
Enable admin to upload more social icon images and more social links on footer social links. 

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/LG#11]
Currently we can only edit the URL link for social media sites and cannot upload any image icons.

Please enable us to add more social media icons of the same size as the site has now, and also add more URL links to the footer. 

![screen shot 2018-09-08 at 6 46 38 pm](https://user-images.githubusercontent.com/12680304/45253301-9d94ac00-b397-11e8-8c43-a75085b591a5.png)

**Comment by mikedesigner** [comment]
Need your help to finish this bug, by fixing the loop on line 66 of footer.php . I have already added the custom fields and everything but  there seems to be an error, **it works and looks fine on the art-types.php page like: http://leung.lordeys.com/en/originals/**     on other pages it shows this error below:

![screen shot 2018-09-11 at 4 06 15 pm](https://user-images.githubusercontent.com/12680304/45347104-cd34f580-b5dd-11e8-99fa-b5bca213046b.png)

**Comment by mikedesigner** [comment]
This footer invalid code issue is now still on this page for example: http://leung.lordeys.com/showcases/ferrari-g500-center/

![screen shot 2018-09-12 at 11 16 26 pm](https://user-images.githubusercontent.com/12680304/45434942-12dae680-b6e2-11e8-84c4-4b040b110d13.png)

**Comment by cezarys** [comment]
the error is gone. 

foreach never checks is the array is an array for real, so I always use something like this:

if(!empty($other_social_links))
{
foreach(...)
}

**Comment by mikedesigner** [comment]
OK great, im not that good at PHP but learning from you.
