### ISSUE TITLE
Originals, Limited Editions, and Open Editions List pages show multiple categories.

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/LG#14]
http://leung.lordeys.com/en/originals/
http://leung.lordeys.com/en/open-editions/
http://leung.lordeys.com/en/limited-editions/

You can edit the php file path which all their archive php files take from here:
 /wp-config/theme/leung/template/artwork-types.php   

the categories filter php loop is probably missing another "if" statement. 

![screen shot 2018-09-10 at 11 17 06 am](https://user-images.githubusercontent.com/12680304/45274783-8d8de100-b4eb-11e8-8f44-2e599da9046e.png)

**Comment by cezarys** [comment]
this one should be done

**Comment by mikedesigner** [comment]
OK I see its done.
