### ISSUE TITLE
Slideshow image resizing on BIG monitors ( we need to find a solution to this tricky problem )

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/LG#17]
So the problem is as the display becomes bigger (for example on 27inch screens - if you have an 5K resolution iMac ) the slideshows are 100% wide and 100% height and cover. What this results is the image will be centered but for an artpiece it will get cut off as parts of it wont be in the visible area.

For example you see this mountain top in the images below looks fine on 13inch macbook airs:
![screen shot 2018-09-12 at 5 47 47 pm](https://user-images.githubusercontent.com/12680304/45418152-561f6000-b6b6-11e8-9b27-9e9f5ca1d7bf.png)

But on bigger monitors the mountain is flying off into space (see below).

![screen shot 2018-09-12 at 5 49 28 pm](https://user-images.githubusercontent.com/12680304/45418254-9252c080-b6b6-11e8-8a88-a2519a10f03e.png)

**Comment by cezarys** [comment]
well, the ony good solution for this was removing "max-height" so now the picture is displayed "as is" keeping the proportions

**Comment by mikedesigner** [comment]
Ok but I had to add some max height back on laptops, and to some bigger monitors otherwise the image becomes super long but past some resolution point I set no max.
