### ISSUE TITLE
Default homepage ( Chinese homepage ) can't be accessed after spending 4+ minutes on the site. Keep redirecting to english homepage when you try to access the Chinese homepage

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/LG#2]

**Comment by cezarys** [comment]
I "think" I fixed it. In the settings http://leung.lordeys.com/wp-admin/admin.php?page=mlang_settings we had "Detect browser language" and this probably messed around. I turned it off and I cleared the cookies, for now seems to work - I can switch between EN and CN on the home page

**Comment by mikedesigner** [comment]
I think so, i will close this, we move on....
